on:
  pull_request_target:
    branches: [main]

jobs:
  evaluator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install yarn
        run: npm install -g yarn

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test:evaluation || true

      - name: Read result of test
        id: resultOutput
        uses: estartandodevs-course/capture-test-result-action@v1.1.0
        with:
          resultPath: /tmp/result.json

      - name: Run evaluator
        id: evaluator
        uses: estartandodevs-course/evaluator-action@v1.1.3
        with:
          testResults: ${{ steps.resultOutput.outputs.resultOfOutputTests }}

      - name: Create comment with evaluation result
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          issue-number: ${{ github.event.number }}
          body: ${{ steps.evaluator.outputs.report }}
